// src/gui/src/components/SearchModal.vue
<template>
  <div v-if="open" class="fixed inset-0 z-50 flex items-start justify-center bg-[rgba(37,24,15,0.3)] p-4 pt-16 backdrop-blur-sm" @click.self="$emit('close')">
    <div class="w-full max-w-2xl overflow-hidden rounded-[28px] border border-[rgba(160,120,80,0.18)] bg-[#fffaf4] shadow-[0_30px_80px_rgba(92,67,50,0.18)]">
      <div class="border-b border-[rgba(160,120,80,0.12)] p-4">
        <div class="flex items-center gap-3 rounded-2xl border border-[rgba(160,120,80,0.16)] bg-white px-4 py-3">
          <Search class="h-4 w-4 text-[rgba(0,0,0,0.32)]" />
          <input
            v-model.trim="query"
            type="text"
            autofocus
            placeholder="搜索对话内容"
            class="w-full bg-transparent text-sm text-[#2a1f13] outline-none placeholder:text-[rgba(0,0,0,0.26)]"
          />
        </div>
      </div>

      <div class="max-h-[60vh] overflow-y-auto p-3">
        <div v-if="loading" class="px-4 py-10 text-center text-sm text-[rgba(0,0,0,0.4)]">搜索中...</div>
        <div v-else-if="query && !results.length" class="px-4 py-10 text-center text-sm text-[rgba(0,0,0,0.4)]">没有匹配结果</div>
        <div v-else class="space-y-2">
          <button
            v-for="result in results"
            :key="result.id"
            type="button"
            class="w-full rounded-2xl border border-transparent bg-white px-4 py-3 text-left transition hover:border-[rgba(160,120,80,0.18)]"
            @click="$emit('select-conversation', result.conversationId)"
          >
            <div class="flex items-center gap-2 text-xs text-[rgba(0,0,0,0.35)]">
              <span class="rounded-full bg-[rgba(160,120,80,0.08)] px-2 py-0.5">{{ result.role === "user" ? "用户" : "AI" }}</span>
              <span>会话 #{{ result.conversationId }}</span>
            </div>
            <div class="mt-2 line-clamp-2 text-sm leading-6 text-[#3d2f1e]">{{ result.content }}</div>
          </button>
        </div>
      </div>

      <div class="flex items-center justify-between border-t border-[rgba(160,120,80,0.12)] px-4 py-3 text-xs text-[rgba(0,0,0,0.38)]">
        <div>{{ page }} / {{ totalPages }}</div>
        <div class="flex items-center gap-2">
          <button type="button" class="rounded-xl px-3 py-2 transition hover:bg-[rgba(160,120,80,0.08)]" :disabled="page <= 1" @click="performSearch(page - 1)">上一页</button>
          <button type="button" class="rounded-xl px-3 py-2 transition hover:bg-[rgba(160,120,80,0.08)]" :disabled="page >= totalPages" @click="performSearch(page + 1)">下一页</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from "vue";
import { Search } from "lucide-vue-next";
import { api } from "@/api";

const props = defineProps({
  open: { type: Boolean, default: false },
});

defineEmits(["close", "select-conversation"]);

const query = ref("");
const results = ref([]);
const page = ref(1);
const totalPages = ref(1);
const loading = ref(false);
let searchTimer = null;

const performSearch = async (nextPage = 1) => {
  if (!query.value) {
    results.value = [];
    page.value = 1;
    totalPages.value = 1;
    return;
  }
  loading.value = true;
  try {
    const res = await api.search(query.value, nextPage);
    if (res.ok) {
      results.value = res.results || [];
      page.value = res.page || 1;
      totalPages.value = res.totalPages || 1;
    }
  } finally {
    loading.value = false;
  }
};

watch(query, () => {
  clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    void performSearch(1);
  }, 250);
});

watch(
  () => props.open,
  (open) => {
    if (!open) return;
    query.value = "";
    results.value = [];
    page.value = 1;
    totalPages.value = 1;
  }
);
</script>

// src/web/src/components/SearchModal.jsx
import { useState, useCallback, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api";
import { Pagination } from "./Pagination";

export function SearchModal({ isOpen, onClose }) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const doSearch = useCallback(async (q, p = 1) => {
    if (!q.trim()) {
      setResults([]);
      setTotalPages(1);
      return;
    }
    setLoading(true);
    try {
      const res = await api.search(q, p);
      if (res.ok) {
        setResults(res.results || []);
        setTotalPages(res.totalPages || 1);
        setPage(res.page || 1);
      }
    } catch (err) {
      console.error("Search error:", err);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    if (query) {
      const timer = setTimeout(() => doSearch(query), 300);
      return () => clearTimeout(timer);
    } else {
      setResults([]);
      setTotalPages(1);
    }
  }, [query, doSearch]);

  const handleResultClick = (baseId) => {
    navigate(`/base/${baseId}`);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-20 bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-gray-900 border border-gray-700 rounded-xl shadow-2xl w-full max-w-2xl animate-fade-in">
        {/* 搜索框 */}
        <div className="p-4 border-b border-gray-800">
          <div className="relative">
            <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="搜索对话内容..."
              className="w-full pl-10 pr-4 py-3 bg-gray-800 border border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
              autoFocus
            />
          </div>
        </div>

        {/* 搜索结果 */}
        <div className="max-h-96 overflow-y-auto">
          {loading ? (
            <div className="p-8 text-center text-gray-500">搜索中...</div>
          ) : results.length === 0 && query ? (
            <div className="p-8 text-center text-gray-500">无结果</div>
          ) : (
            <ul className="divide-y divide-gray-800">
              {results.map((r) => (
                <li key={r.id}>
                  <button
                    onClick={() => handleResultClick(r.baseId)}
                    className="w-full p-4 text-left hover:bg-gray-800 transition-colors"
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`text-xs px-2 py-0.5 rounded ${
                        r.role === "user" ? "bg-blue-900/50 text-blue-300" : "bg-purple-900/50 text-purple-300"
                      }`}>
                        {r.role === "user" ? "用户" : "AI"}
                      </span>
                      <span className="text-xs text-gray-500">
                        会话 #{r.baseId}
                      </span>
                    </div>
                    <p className="text-sm text-gray-300 truncate">
                      {r.content}
                    </p>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* 分页 */}
        {totalPages > 1 && (
          <div className="p-3 border-t border-gray-800">
            <Pagination page={page} totalPages={totalPages} onPageChange={(p) => doSearch(query, p)} />
          </div>
        )}

        {/* 底部 */}
        <div className="p-3 border-t border-gray-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm text-gray-400 hover:text-gray-200"
          >
            关闭
          </button>
        </div>
      </div>
    </div>
  );
}
